version: '3'

services:
  db:
    container_name: rust-recipe-gallery-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    image: postgres:15.3-bullseye
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rust_recipe_gallery
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env

  backend:
    container_name: rust-recipe-gallery-backend
    restart: unless-stopped
    build: .
    ports:
      - "${RUST_RECIPE_GALLERY_BACKEND_PORT}:${RUST_RECIPE_GALLERY_BACKEND_PORT}"
    depends_on:
      - db
    networks:
      - rust_recipe_gallery
    env_file:
      - .env

networks:
  rust_recipe_gallery:


volumes:
  postgres_data:
